DATA SEGMENT
	ARR DB 03H,05H,09H,10H,0AH,02H
	MSG1 DB 10,13, "ENTER TWO DIGIT NUMBER TO BE SEARCHED$"
	MSG2 DB 10,13, "NUMBER FOUND$"
	MSG3 DB 10,13, "NUMBER NOT FOUND$"
	NO DB ?
DATA ENDS
CODE SEGMENT
ASSUME DS:DATA, CS:CODE
START:
		MOV AX,DATA
		MOV DS,AX
		MOV AX,0000H
		LEA DX,MSG1
		MOV AH,09H
		INT 21H
		CALL INPUT
		MOV NO,BL
		LEA SI,ARR
		MOV CL,06H
AGAIN:	MOV BL,[SI]
		CMP BL,NO
		JZ FOUND
		INC SI
		DEC CL
		JZ NOTFOUND
		JMP AGAIN
FOUND:	LEA DX,MSG2
		MOV AH,09H
		INT 21H
		JMP BYE
NOTFOUND:LEA DX,MSG3
		MOV AH,09H
		INT 21H 		
BYE:	MOV AH,4CH
		INT 21H
		
		
		
	INPUT PROC
		MOV AH,01H
		INT 21H
		CMP AL,41H
		JC LAB1
		SUB AL,07H
LAB1:	SUB AL,30H
		MOV BL,AL
		ROL BL,04H
		MOV AH,01H
		INT 21H
		CMP AL,41H
		JC LAB2
		SUB AL,07H
LAB2:	SUB AL,30H
		ADD AL,BL
		RET
	ENDP
	
	
CODE ENDS
END START
